spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MY_EMAIL_USER}
spring.mail.password=${MY_EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory